### ISSUE TITLE
Better String -> ByteString instances?

### ISSUE THREAD

**Issue by mightybyte** [Soostone/string-conv#3]
https://www.reddit.com/r/haskell/comments/4p2vx7/what_can_i_do_to_help_the_stringbytestringtext/d4i2pfk

**Comment by MichaelXavier** [comment]
So am I understanding this correctly that the instance for `StringConv String ByteString` should be something like `stringConv leniency = Data.Text.Encoding.encodeUtf8 . stringConv leniency`?

**Comment by mightybyte** [comment]
That's what it sounds like to me.

**Comment by MichaelXavier** [comment]
This will get released as 0.1.2
